# Generated by Django 3.2.3 on 2021-06-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_smoking_yn',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Refused')], null=True, verbose_name='Are you a current or former smoker?'),
        ),
    ]
