# Generated by Django 3.2.3 on 2021-06-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_alter_screen_screen_smoking_yn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_20packyears_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='B1b. Based on your calculation, does the subject have 10 pack-year smoking history?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Specify age:'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_bph_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have Benign Prostatic Hyperplasia (BPH)?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_diabetes_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have Diabetes Type I?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_dx_additional_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have narrow-angle glaucoma, bladder-neck obstruction or severe renal impairment or urinary retention?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Refused')], null=True, verbose_name='Please confirm your gender'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_hx_asthma_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Please provide age when diagnosed.'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_hx_asthma_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have a history of asthma?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_hx_atrialfibrillation_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have a history of atrial fibrillation?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_hx_lungdisease_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have a history of lung disease?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_investigationaldrug_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Are you currently or have you in the past 30 days participated in any other clinical trials involving an investigational drug?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_lungcancer_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have lung cancer or a history of lung cancer?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_packyears',
            field=models.IntegerField(blank=True, null=True, verbose_name='Packyear Calculation Result'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_pregnancy_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='(FEMALES ONLY) Are you pregnant, breast-feeding, or planning to become pregnant in the next 3 months?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_rx_respiratoryinfection_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='C2. Have you received a course of antibiotics or systemic steroids for respiratory infection within the past 4 weeks?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_smoking_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many packs do or did you smoke per day?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_smoking_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many years have you (or had you) smoked?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_smoking_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Are you a current or former smoker?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_therapy_atrialfibrillation_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Have you been on therapy for your atrial fibrillation for 6 months or more?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_treatment_atrialfibrillation_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Has your atrial fibrillation been well controlled with treatment for 6 months or more?'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='screen_treatment_bph_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you have Benign Prostatic Hyperplasia (BPH)?'),
        ),
    ]
