# Generated by Django 3.2.3 on 2021-06-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_screen_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_treatment_bph_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Are you on stable treatment for BPH?'),
        ),
    ]
