# Generated by Django 3.2.3 on 2021-06-02 03:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=50, verbose_name='First Name')),
                ('name_middle', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('name_last', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Primary Phone Number')),
                ('phone1_type', models.IntegerField(choices=[(1, 'Landline'), (2, 'Cell')], verbose_name='Type of Phone')),
                ('phone1_text_yn', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Are you willing to receive text messages at this number?')),
                ('contact_basetime_survey', models.IntegerField(choices=[(1, 'AM'), (2, 'PM')], verbose_name='When is the best time to contact you?')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Secondary Phone Number')),
                ('phone2_type', models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'Cell')], null=True, verbose_name='Type of Phone')),
                ('phone2_text_yn', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Are you willing to receive text messages at this number?')),
                ('address1', models.CharField(max_length=100, verbose_name='Address 1 (Building no. & Street name)')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Address 2 (If applicable, Unit/Apt no.)')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.IntegerField(choices=[(13, 'Illinois'), (1, 'Alabama'), (2, 'Alaska'), (3, 'Arizona'), (4, 'Arkansas'), (5, 'California'), (6, 'Colorado'), (7, 'Connecticut'), (8, 'Delaware'), (9, 'Florida'), (10, 'Georgia'), (11, 'Hawaii'), (12, 'Idaho'), (14, 'Indiana'), (15, 'Iowa'), (16, 'Kansas'), (17, 'Kentucky'), (18, 'Louisiana'), (19, 'Maine'), (20, 'Maryland'), (21, 'Massachusetts'), (22, 'Michigan'), (23, 'Minnesota'), (24, 'Mississippi'), (25, 'Missouri'), (26, 'Montana'), (27, 'Nebraska'), (28, 'Nevada'), (29, 'New Hampshire'), (30, 'New Jersey'), (31, 'New Mexico'), (32, 'New York'), (33, 'North Carolina'), (34, 'North Dakota'), (35, 'Ohio'), (36, 'Oklahoma'), (37, 'Oregon'), (38, 'Pennsylvania'), (39, 'Rhode Island'), (40, 'South Carolina'), (41, 'South Dakota'), (42, 'Tennessee'), (43, 'Texas'), (44, 'Utah'), (45, 'Vermont'), (46, 'Virginia'), (47, 'Washington'), (48, 'West Virginia'), (49, 'Wisconsin'), (50, 'Wyoming')], verbose_name='State')),
                ('zipcode', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('voicemail_yn_survey', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='May the UIC Breathe Chicago Center leave you a voicemail the above number?')),
                ('copd_yn_survey', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='Has a doctor told you that you have Chronic Obstructive Pulmonary Disease (COPD)?')),
                ('copd_exacerbation_yn_survey', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Have you had a COPD exacerbation (flare-up) requiring treatment within the last 6 weeks')),
                ('smoking_yn_survey', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='Have you ever smoked cigarettes?')),
                ('smoking_now_yn_survey', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you now smoke cigarettes (as of 1 month ago)?')),
                ('smoking_start_survey', models.IntegerField(blank=True, null=True, verbose_name='How old were you when you first started regular cigarette smoking?')),
                ('smoking_stop_survey', models.IntegerField(blank=True, null=True, verbose_name='If you stopped smoking cigarettes completely, how old were you when you stopped?')),
                ('smoking_amount_survey', models.IntegerField(blank=True, null=True, verbose_name='On the average of the entire time you smoked, how many cigarettes do/did you smoke per day? (20 cigarettes = 1 pack)?')),
                ('rx_bp_yn_survey', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='Are you using any blood pressure medicines?')),
                ('rx_bp_survey', models.CharField(blank=True, max_length=300, verbose_name='Please list the blood pressure medicine you currently use.')),
                ('recruitment_source_survey', models.IntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Email'), (4, 'Flyers'), (5, 'Craigslist'), (6, 'Referral'), (99, 'Other')], verbose_name='Where did you hear about us?')),
                ('recruitment_source_other_survey', models.CharField(blank=True, max_length=100, verbose_name="Please specify 'Other'")),
                ('current_age', models.IntegerField(blank=True, verbose_name='Current Age')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Refused')], verbose_name='5. Gender')),
                ('race', models.IntegerField(choices=[(1, 'American Indian/Alaskan Native'), (2, 'Asian'), (3, 'Black/African American'), (4, 'Native Hawaiian/Pacific Islander'), (5, 'Whtie'), (6, 'Other'), (7, 'Unknown')], verbose_name='5.1. Race')),
                ('ethnicity', models.IntegerField(choices=[(1, 'Hispanic/Latino'), (2, 'Not Hispanic/Latino'), (3, 'Unknown')], verbose_name='5.2. Ethnicity')),
                ('email_yn', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='13. Do you have an e-mail address?')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at:')),
            ],
            options={
                'unique_together': {('name_first', 'name_last', 'dob', 'phone1')},
            },
        ),
    ]
