# Generated by Django 3.2.3 on 2021-06-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='contact_basetime_survey',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], verbose_name='When is the best time to contact you?'),
        ),
    ]
