# Generated by Django 3.2.3 on 2021-06-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='current_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Age'),
        ),
    ]
