# Generated by Django 3.2.3 on 2021-06-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_patientinfo_current_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinfo',
            name='created_at',
        ),
    ]
