# Generated by Django 3.2.3 on 2021-06-02 00:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_patientinfo_contact_basetime_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='copd_exacerbation_yn_survey',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Have you had a COPD exacerbation (flare-up) requiring treatment within the last 6 weeks'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='phone1_text_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Are you willing to receive text messages at this number?'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Secondary Phone Number'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='phone2_text_yn',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Are you willing to receive text messages at this number?'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='phone2_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Home'), (2, 'Cell')], null=True, verbose_name='Type of Phone'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='smoking_amount_survey',
            field=models.IntegerField(blank=True, null=True, verbose_name='On the average of the entire time you smoked, how many cigarettes do/did you smoke per day? (20 cigarettes = 1 pack)?'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='smoking_now_yn_survey',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Do you now smoke cigarettes (as of 1 month ago)?'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='smoking_start_survey',
            field=models.IntegerField(blank=True, null=True, verbose_name='How old were you when you first started regular cigarette smoking?'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='smoking_stop_survey',
            field=models.IntegerField(blank=True, null=True, verbose_name='If you stopped smoking cigarettes completely, how old were you when you stopped?'),
        ),
    ]
