# Generated by Django 3.2.3 on 2021-06-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZipcodeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('week', models.IntegerField(verbose_name='Week Number')),
                ('cases', models.IntegerField(verbose_name='Weekly Cases')),
                ('tests', models.IntegerField(verbose_name='Weekly Tests')),
                ('deaths', models.IntegerField(verbose_name='Weekly Deaths')),
            ],
            options={
                'unique_together': {('zipcode', 'week')},
            },
        ),
    ]
